AppMVC/Models/Product.cs
using AppMVC.Data.Base;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppMVC.Models
{
    public class Product : IEntityBase
    {
        [Key]
        public int Id { get; set; }
        public string ImageUrl { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public DateTime createdAt { get; set; }

        //Relationships
        //Supplier
        public int SupplierId { get; set; }
        [ForeignKey("SupplierId")]
        public Supplier Supplier { get; set; }
        //Category
        public int CategoryId { get; set; }
        [ForeignKey("CategoryId")]
        public Category Category { get; set; }



    }
}

AppMVC/Controllers/CategoriesController.cs
using AppMVC.Data;
using AppMVC.Data.Services;
using AppMVC.Data.Static;
using AppMVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AppMVC.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class CategoriesController : Controller
    {
        private readonly ICategoriesService _service;
        private readonly ILogger<CategoriesController> _logger;
        public CategoriesController(ICategoriesService service, ILogger<CategoriesController> logger)
        {
            _service = service;
            _logger = logger;
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allCategories = await _service.GetAllAsync();
            return View(allCategories);
        }
        //Get: categorys/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("ImageUrl,Title,Description")] Category category)
        {
            if (!ModelState.IsValid) return View(category);
            await _service.AddAsync(category);
            return RedirectToAction(nameof(Index));
        }

        //Get: Categories/Details/1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var categoryDetails = await _service.GetByIdAsync(id);
            if (categoryDetails == null) return View("NotFound");
            return View(categoryDetails);
        }

        //Get: Categories/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var categoryDetails = await _service.GetByIdAsync(id);
            if (categoryDetails == null) return View("NotFound");
            return View(categoryDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ImageUrl,Title,Description")] Category category)
        {
            if (!ModelState.IsValid) return View(category);
            await _service.UpdateAsync(id, category);
            return RedirectToAction(nameof(Index));
        }

        //Get: categorys/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var categoryDetails = await _service.GetByIdAsync(id);
            if (categoryDetails == null) return View("NotFound");
            return View(categoryDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var categoryDetails = await _service.GetByIdAsync(id);
            if (categoryDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

AppMVC/Controllers/ProductsController.cs
using AppMVC.Data;
using AppMVC.Data.Services;
using AppMVC.Data.Static;
using AppMVC.Data.ViewModels;
using AppMVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;
using System.Collections;
using System.Diagnostics;
using System.Diagnostics.Eventing.Reader;

namespace AppMVC.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class ProductsController : Controller
    {
        private readonly IProductsService _service;
        private readonly ILogger<ProductsController> _logger;
        private readonly IMemoryCache _cache;
        private readonly string cacheKey = "productsCacheKey";
        public ProductsController(IProductsService service, ILogger<ProductsController> logger, IMemoryCache cache )
        {
            _service = service;
            _logger = logger;
            _cache = cache;
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            _logger.LogInformation($"Controller Trying to get all products at :{DateTime.Now.TimeOfDay} ");
            _logger.Log(LogLevel.Information, "Trying to get all products");
            var stopWatch = new Stopwatch();
            stopWatch.Start();

            if (_cache.TryGetValue(cacheKey, out IEnumerable<Product> allProducts))
            {
                _logger.Log(LogLevel.Information, "Products found in cache");
            }
            else
            {
                _logger.Log(LogLevel.Information, "Products NOT found in cache, Loading ...");

                allProducts = await _service.GetAllAsync(n => n.Category);

                var cacheEntryOptions = new MemoryCacheEntryOptions()
                    .SetSlidingExpiration(TimeSpan.FromSeconds(45))
                    .SetAbsoluteExpiration(TimeSpan.FromSeconds(3600))
                    .SetPriority(CacheItemPriority.Normal);

                _cache.Set(cacheKey, allProducts, cacheEntryOptions);
            }
            stopWatch.Stop();
            _logger.Log(LogLevel.Information, $"Passed Time: {stopWatch.ElapsedMilliseconds} ms");
            return View(allProducts);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Filter(string searchString)
        {
            var allProducts = await _service.GetAllAsync(n => n.Category);
            _logger.Log(LogLevel.Information, "Filtrage");
            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResultNew = allProducts
                    .Where(n => n.Title.Contains(searchString, StringComparison.CurrentCultureIgnoreCase) ||
                                n.Description.Contains(searchString, StringComparison.CurrentCultureIgnoreCase))
                    .ToList();
                _logger.Log(LogLevel.Information, $"Filrtrage String : {searchString}");
                _logger.Log(LogLevel.Information, $"Count Products : {filteredResultNew.Count}");
                return View("Index", filteredResultNew);
            }

            return View("Index", allProducts);
        }

        //GET: Products/Details/1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var productDetail = await _service.GetProductByIdAsync(id);
            return View(productDetail);
        }

        //GET: Products/Create
        public async Task<IActionResult> Create()
        {
            var productDropdownsData = await _service.GetNewProductDropdownsValues();

            ViewBag.Categories = new SelectList(productDropdownsData.Categories, "Id", "Title");
            ViewBag.Suppliers = new SelectList(productDropdownsData.Suppliers, "Id", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewProductVM product)
        {
            if (!ModelState.IsValid)
            {
                var productDropdownsData = await _service.GetNewProductDropdownsValues();

                ViewBag.Categories = new SelectList(productDropdownsData.Categories, "Id", "Title");
                ViewBag.Suppliers = new SelectList(productDropdownsData.Suppliers, "Id", "Name");

                return View(product);
            }

            await _service.AddNewProductAsync(product);
            return RedirectToAction(nameof(Index));
        }

        //GET: Products/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var productDetails = await _service.GetProductByIdAsync(id);
            if (productDetails == null) return View("NotFound");

            var response = new NewProductVM()
            {
                Id = productDetails.Id,
                Title = productDetails.Title,
                Description = productDetails.Description,
                Price = productDetails.Price,
                createdAt = productDetails.createdAt,
                ImageUrl = productDetails.ImageUrl,
                CategoryId = productDetails.CategoryId,
                SupplierId = productDetails.SupplierId,
            };

            var productDropdownsData = await _service.GetNewProductDropdownsValues();

            ViewBag.Categories = new SelectList(productDropdownsData.Categories, "Id", "Title");
            ViewBag.Suppliers = new SelectList(productDropdownsData.Suppliers, "Id", "Name");


            return View(response);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewProductVM product)
        {
            if (id != product.Id) return View("NotFound");

            if (!ModelState.IsValid)
            {
                var productDropdownsData = await _service.GetNewProductDropdownsValues();

                ViewBag.Categories = new SelectList(productDropdownsData.Categories, "Id", "Title");
                ViewBag.Suppliers = new SelectList(productDropdownsData.Suppliers, "Id", "Name");

                return View(product);
            }

            await _service.UpdateProductAsync(product);
            return RedirectToAction(nameof(Index));
        }

    }
}

AppMVC/Controllers/SuppliersController.cs
using AppMVC.Data;
using AppMVC.Data.Services;
using AppMVC.Data.Static;
using AppMVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
namespace AppMVC.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class SuppliersController : Controller
    {
        private readonly ISuppliersService _service;
        private readonly ILogger<SuppliersController> _logger;
        public SuppliersController(ISuppliersService service, ILogger<SuppliersController> logger)
        {
            _service = service;
            _logger = logger;
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allSuppliers = await _service.GetAllAsync();
            return View(allSuppliers);
        }
        //Get: suppliers/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("ImageUrl,Name,Description")] Supplier supplier)
        {
            if (!ModelState.IsValid) return View(supplier);
            await _service.AddAsync(supplier);
            return RedirectToAction(nameof(Index));
        }

        //Get: Suppliers/Details/1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var supplierDetails = await _service.GetByIdAsync(id);
            if (supplierDetails == null) return View("NotFound");
            return View(supplierDetails);
        }

        //Get: Suppliers/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var supplierDetails = await _service.GetByIdAsync(id);
            if (supplierDetails == null) return View("NotFound");
            return View(supplierDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ImageUrl,Name,Description")] Supplier supplier)
        {
            if (!ModelState.IsValid) return View(supplier);
            await _service.UpdateAsync(id, supplier);
            return RedirectToAction(nameof(Index));
        }

        //Get: suppliers/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var supplierDetails = await _service.GetByIdAsync(id);
            if (supplierDetails == null) return View("NotFound");
            return View(supplierDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var supplierDetails = await _service.GetByIdAsync(id);
            if (supplierDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

AppMVC/Views/Products/Create.cshtml
@model NewProductVM
@using AppMVC.Data.ViewModels;

@{
    ViewData["Title"] = "Create product";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Create product</h4>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Title" class="control-label"></label>
                                <input asp-for="Title" class="form-control" />
                                <span asp-validation-for="Title" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="createdAt" class="control-label"></label>
                                <input asp-for="createdAt" type="date" class="form-control" />
                                <span asp-validation-for="createdAt" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Price" class="control-label"></label>
                                <input asp-for="Price" type="number" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ImageUrl" class="control-label"></label>
                                <input asp-for="ImageUrl" class="form-control" />
                                <span asp-validation-for="ImageUrl" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="CategoryId" class="control-label"></label>
                                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.Categories"></select>
                                <span asp-validation-for="CategoryId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="SupplierId" class="control-label"></label>
                                <select asp-for="SupplierId" class="form-control" asp-items="ViewBag.Suppliers"></select>
                                <span asp-validation-for="SupplierId" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4 offset-4 text-center">
                        <img width="100%" id="ImageUrlPreview" />
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                    </div>

                </form>

            </div>
        </div>

    </div>
</div>

@section Scripts{
    <script>
        

        $("#ImageUrl").on("change", function () {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $(this).val();
        })
    </script>
}

AppMVC/Views/Products/Details.cshtml
@model Product

@{
    ViewData["Title"] = "Products details";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <div class="card mb-12">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white bg-danger">
                        <p class="card-text">
                            <h5 class="card-title">
                                @Model.Title
                            </h5>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="@Model.ImageUrl" width="100%" alt="@Model.Title">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text">@Model.Description</p>
                        <p class="card-text">
                            <b>Category: </b>
                            <a asp-controller="Categories" asp-action="Details" asp-route-id="@Model.CategoryId">
                                @Model.Category.Title
                            </a>
                        </p>
                        <p class="card-text">
                            <b>Supplier: </b>
                            <a asp-controller="Suppliers" asp-action="Details" asp-route-id="@Model.SupplierId">
                                @Model.Supplier.Name
                            </a>
                        </p
                        <p class="card-text"><b>Start Date: </b>@Model.createdAt.ToString("dd MMM yy")</p>
                        @* <p class="card-text ">
                            <b>Status: </b>
                            @if (DateTime.Now >= Model.StartDate && DateTime.Now <= Model.EndDate)
                            {
                                <span class="badge bg-success text-white">AVAILABLE</span>
                            }
                            else if (DateTime.Now > Model.EndDate)
                            {
                                <span class="badge bg-danger text-white">EXPIRED</span>
                            }
                            else
                            {
                                <span class="badge bg-primary text-white">UPCOMING</span>
                            }
                        </p> *@
                        

                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card-footer">
                        <p class="card-text">
                            <a class="btn btn-outline-primary float-right" asp-action="Index">
                                Back to List
                            </a>
                            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                            { 
                                <a class="btn btn-success text-white"
                                asp-controller="Products"
                                asp-action="Edit"
                                asp-route-id="@Model.Id">
                                    <i class="bi bi-pencil-square"></i> Edit
                                </a>
                            }
                            else
                            {
                            <a class="btn btn-dark text-white"
                                asp-controller="Orders"
                                asp-action="AddItemToShoppingCart"
                                asp-route-id="@Model.Id">
                                <i class="bi bi-cart-plus"></i> Add to Cart (Price @Model.Price.ToString("c"))
                            </a>
                            }
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

AppMVC/Views/Products/Edit.cshtml
@model NewProductVM
@using AppMVC.Data.ViewModels;

@{
    ViewData["Title"] = "Update product";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Update product</h4>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Title" class="control-label"></label>
                                <input asp-for="Title" class="form-control" />
                                <span asp-validation-for="Title" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="createdAt" class="control-label"></label>
                                <input asp-for="createdAt" type="date" class="form-control" />
                                <span asp-validation-for="createdAt" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Price" class="control-label"></label>
                                <input asp-for="Price" type="number" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ImageUrl" class="control-label"></label>
                                <input asp-for="ImageUrl" class="form-control" />
                                <span asp-validation-for="ImageUrl" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="CategoryId" class="control-label"></label>
                                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.Categories"></select>
                                <span asp-validation-for="CategoryId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="SupplierId" class="control-label"></label>
                                <select asp-for="SupplierId" class="form-control" asp-items="ViewBag.Suppliers"></select>
                                <span asp-validation-for="SupplierId" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4 offset-4 text-center">
                        <img width="100%" id="ImageUrlPreview" />
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Update" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                    </div>

                </form>

            </div>
        </div>

    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $("#ImageUrl").val();
        });

        $("#ImageUrl").on("change", function () {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $(this).val();
        })
    </script>
}

AppMVC/Views/Products/Index.cshtml
@model IEnumerable<Product>

@{
    ViewData["Title"] = "List of Products";
}

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-danger">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.Title
                                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                    {
                                        <a class="text-white float-right" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
                                    }
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.ImageUrl" width="100%" alt="@item.Title">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text">@item.Description</p>
                           @*  <p class="card-text"><b>Supplier: </b>@item.Supplier.Name</p> *@
                            @* <p class="card-text"><b>Category: </b>@item.Category.Title</p> *@
                            <p class="card-text"><b>Date: </b>@item.createdAt.ToString("dd MMM yy")</p>
                            @* <p class="card-text"><b>End Date: </b>@item.EndDate.ToString("dd MMM yy")</p> *@
                            @* <p class="card-text ">
                                <b>Status: </b>
                                @if (DateTime.Now >= item.StartDate && DateTime.Now <= item.EndDate)
                                {
                                    <span class="badge bg-success text-white">AVAILABLE</span>
                                }
                                else if (DateTime.Now > item.EndDate)
                                {
                                    <span class="badge bg-danger text-white">EXPIRED</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary text-white">UPCOMING</span>
                                }
                            </p> *@

                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-right" asp-action="Details" asp-route-id="@item.Id">
                                    <i class="bi bi-eye-fill"></i> Show Details
                                </a>
                                @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                { 
                                    <a class="btn btn-success text-white"
                                    asp-controller="Products"
                                    asp-action="Details"
                                    asp-route-id="@item.Id">
                                        <i class="bi bi-ticket-detailed"></i> Details
                                    </a>
                                }
                                else
                                {
                                    <a class="btn btn-dark text-white"
                                       asp-controller="Orders"
                                       asp-action="AddItemToShoppingCart"
                                       asp-route-id="@item.Id">
                                        <i class="bi bi-cart-plus"></i> Add to Cart (Price @item.Price.ToString("c"))
                                    </a>
                                }
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>
@await Html.PartialAsync("_CreateItem", "Products") 